/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    12HourTimeAtom: typeof import('./src/components/atoms/12HourTimeAtom.vue')['default']
    AccountIcon: typeof import('./src/components/icons/AccountIcon.vue')['default']
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    ArrowRightIcon: typeof import('./src/components/icons/ArrowRightIcon.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BackArrowIcon: typeof import('./src/components/icons/BackArrowIcon.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonAtom: typeof import('./src/components/atoms/ButtonAtom.vue')['default']
    CityList: typeof import('./src/components/molecules/CityList.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    FormAtom: typeof import('./src/components/atoms/FormAtom.vue')['default']
    HourlyForecastList: typeof import('./src/components/organisms/HourlyForecastList.vue')['default']
    HourlyWeatherCard: typeof import('./src/components/molecules/HourlyWeatherCard.vue')['default']
    InputAtom: typeof import('./src/components/atoms/InputAtom.vue')['default']
    LabelAtom: typeof import('./src/components/atoms/LabelAtom.vue')['default']
    MainWeatherCard: typeof import('./src/components/molecules/MainWeatherCard.vue')['default']
    OpenWeatherIconAtom: typeof import('./src/components/atoms/OpenWeatherIconAtom.vue')['default']
    ProfileDetails: typeof import('./src/components/molecules/ProfileDetails.vue')['default']
    ProfileForm: typeof import('./src/components/molecules/ProfileForm.vue')['default']
    ProfilePicture: typeof import('./src/components/molecules/ProfilePicture.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RefreshIcon: typeof import('./src/components/icons/RefreshIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkButton: typeof import('./src/components/molecules/RouterLinkButton.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SavedWeatherCard: typeof import('./src/components/molecules/SavedWeatherCard.vue')['default']
    SavedWeatherList: typeof import('./src/components/organisms/SavedWeatherList.vue')['default']
    SearchCityInputField: typeof import('./src/components/organisms/SearchCityInputField.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    TemperatureAtom: typeof import('./src/components/atoms/TemperatureAtom.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TrashIcon: typeof import('./src/components/icons/TrashIcon.vue')['default']
    UploadImageIcon: typeof import('./src/components/icons/UploadImageIcon.vue')['default']
    WeeklyForecastList: typeof import('./src/components/organisms/WeeklyForecastList.vue')['default']
    WeeklyWeatherCard: typeof import('./src/components/molecules/WeeklyWeatherCard.vue')['default']
  }
}
